### ISSUE TITLE
上传图片后报500？

### ISSUE THREAD

**Issue by wadewtwt** [liu-ziting/petThoughts#1]
![image](https://github.com/liu-ziting/PetThoughts/assets/29997297/885b94bb-d4d4-43d4-b918-231c5f329862)

**Comment by liu-ziting** [comment]
已经解决了，因为昨天gemini key 被封了，可能近期也会封

**Comment by liu-ziting** [comment]
已经解决了，因为昨天gemini key 被封了，可能近期也会封，可以自己申请调用。
